# Pydantic schemas
from pydantic import BaseModel, Field
from typing import List, Optional

class Product(BaseModel):
    """Represents a single shopping item."""
    id: str = Field(description="Unique ID or URL hash of the item")
    title: str = Field(description="The name of the product")
    price: str = Field(description="The price string, e.g., '$149.99'")
    currency: str = Field(default="USD")
    rating: Optional[float] = Field(description="Review score 0-5", default=None)
    image_url: str = Field(description="Main image URL")
    product_url: str = Field(description="Link to purchase")
    description: str = Field(description="Short summary of the item")
    source: str = Field(description="Where it came from (e.g., 'Amazon', 'Nike')")

class SearchPlan(BaseModel):
    """The strategy generated by the Planner Agent."""
    search_queries: List[str] = Field(description="List of specific search terms to try")
    min_price: Optional[float] = None
    max_price: Optional[float] = None
    must_have_features: List[str] = []
    avoid_keywords: List[str] = []