# backend/src/agent/state.py
# Every agent receives this state, modifies it, and passes it to the next node
from typing import List, Annotated, TypedDict
from langchain_core.messages import BaseMessage
import operator
from .models import Product, SearchPlan

class AgentState(TypedDict):
    # 1. Conversation History (Standard LangChain messages)
    # Annotated[..., operator.add] means "append new messages to the list"
    messages: Annotated[List[BaseMessage], operator.add]

    # 2. The User's Request
    original_query: str

    # 3. The Plan (Generated by Planner Agent)
    search_plan: SearchPlan

    # 4. Raw Findings (The messy pile of data from the Search Agent)
    raw_search_results: List[dict]

    # 5. The Clean List (The curated stack shown to the user)
    curated_products: List[Product]

    # 6. User Feedback (The "Swipe" history)
    # e.g., {'rejected_ids': ['123', '456'], 'liked_ids': ['789']}
    feedback: dict